package springboot.spring.entity;

import javax.persistence.*;


@Entity
@Table( name = "User" )
public class User {

    @Id
    @GeneratedValue( strategy = GenerationType.AUTO ) //the id field will be automatically generated by the database
    private Long id;

    @Column( name = "firstname" )
    //@NotNull
    //@Min(3)
    private String firstname;

    //@NotNull
    //@Min(3)
    @Column( name = "lastname" )
    private String lastname;

    //@NotNull
    @Column( name = "email" )
    private String email;

    //@NotNull
    @Column( name = "contact" )
    private String contact;

    //@NotNull
    //@Size(min = 6,max=34)
    @Column( name = "username" )
    private String username;


    @Column( name = "password" )
    //@NotNull
    //@Size(min = 5,max=12)
    private String password;

    @Transient //for checking the similarity with the password the user will put in the password field
    //@NotNull
    private String confirmPassword;


    //constructor info
    public User(String firstname, String lastname, String email, String contact, String username, String password) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
        this.contact = contact;
        this.username = username;
        this.password = password;
    }

    public String getConfirmPassword() {
        return confirmPassword;
    }

    public void setConfirmPassword(String confirmPassword) {
        this.confirmPassword = confirmPassword;
    }

    public String getFirstname() {
        return firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getContact() {
        return contact;
    }

    public void setContact(String contact) {
        this.contact = contact;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }


}
